<?php
return array(
    'sds' => array(
        'authentication' => array(

            'authenticationAdapter' => 'doctrine.authenticationadapter.odm_default',

            'authenticationStorage' => 'doctrine.authenticationstorage.odm_default',

            //Used to serialize objects
            'serializer' => 'sds.doctrineExtensions.serializer',

            'enableAccessControl' => false,
        ),

        //The path to place smd generated by the generate-json-rpc-smd command line tool
        'jsonRpcSmdGenerator' => array(
            'sds.authentication' => array(
                'path' => 'vendor/dojo/Sds/AuthenticationModule/Smd.js',
                'format' => 'dojo', // dojo | json
                'target' => 'http://localhost/ZendSkeletonApplication/authentication', //Override this target in your own config
            ),
        ),

        //Only used if sds accessControl is in use
        'accessControl' => array(
            'controllers' => array(
                'authentication' => array(
                    'jsonRpc' => true,
                    'methods' => array(
                        'serviceMap' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                        'login' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                        'logout' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::user
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),

    'doctrine' => array(
        'authentication' => array(
            'odm_default' => array(
                'identityClass' => 'Sds\UserModule\DataModel\User',
                'credentialCallable' => 'Sds\Common\Crypt\Hash::hashCredential'
            )
        ),
    ),

    'router' => array(
        'routes' => array(
            'sds.authentication' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/auth',
                    'defaults' => array(
                        'controller' => 'sds.authentication',
                    ),
                ),
            ),
        ),
    ),

    'controllers' => array(
        'factories' => array(
            'sds.authentication' => 'Sds\AuthModule\Service\AuthenticationControllerFactory'
        ),
    ),

    'view_manager' => array(
        'strategies' => array(
            'ViewJsonStrategy',
        ),
    ),

    'service_manager' => array(
        'factories' => array(
            'Zend\Authentication\AuthenticationService' => 'Sds\AuthenticationModule\Service\AuthenticationServiceFactory'
        )
    )
);
